birthday:
    csv: bday.csv
    email:
        subject: "Birthday Wishes to {name}"
        sender:
            userid: "sender@mail.net"
            passwd: "send_password"
        receivers:
            - "recv@mail.net"
        body: "
            Dear %s,
            
            On Behalf of the our Company Family
            
            We Wish You A Very Happy Birthday
            
            Cheers,
            From Company Family 
            "
